"""create account table

Revision ID: 7077af9276f1
Revises: 
Create Date: 2021-12-05 14:31:28.703755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7077af9276f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neosbooks__books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neosbooks__books_id'), 'neosbooks__books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_neosbooks__books_id'), table_name='neosbooks__books')
    op.drop_table('neosbooks__books')
    # ### end Alembic commands ###
